DL:
  Gallery:
    Map:
      gmaps:
        width: "100%"
        height: "450px"
        showRouteToLink: false
        dropAnimation: true
        cluster: true
        langCode: de
        showAllMarkers: true
        showFirstMarkerOnStart: false
        lightbox: true
        mapOptions:
          zoom: 14
          streetViewControl: false
          mapTypeControl: false
          panControl: false



Neos:
  Neos:
    fusion:
      autoInclude:
        DL.Gallery.Map: true
