DL:
  Gallery:
    Map:
      gmaps:
        width: "100%"
        height: "600px"
        showRouteToLink: false
        dropAnimation: true
        cluster: true
        langCode: de
        showAllMarkers: true
        showFirstMarkerOnStart: false
        lightbox: true

        marker:
          width: 50
          height: 50

        thumb:
          width: 200
          height: 200

        mapOptions:
          zoom: 14
          streetViewControl: false
          mapTypeControl: false
          panControl: false



Neos:
  Neos:
    fusion:
      autoInclude:
        DL.Gallery.Map: true
